version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - docker build -t pms-api .
      - docker tag pms-api:latest $ECR_URI:prod-latest

  post_build:
    commands:
      - docker push $ECR_URI:prod-latest
      - printf '[{"name":"nestjs-api","imageUri":"%s"}]' $ECR_URI:prod-latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json