export const jwtConstants = {
  secret:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP IT SAFE OUTSIDE OF THE SOURCE CODE.',
};

export enum Role {
  SYSTEM_SUPER_ADMIN = 'SYSTEM_SUPER_ADMIN',
  SYSTEM_SUPPORT = 'SYSTEM_SUPPORT',

  COMPANY_ADMIN = 'COMPANY_ADMIN',
  SUPERINTENDENT = 'SUPERINTENDENT',
  TECHNICAL_MANAGER = 'TECHNICAL_MANAGER',

  ENGINEER = 'ENGINEER',
  CREW = 'CREW',
  VIEWER = 'VIEWER',
}
